version: 2

registries:
    github-packages:
        type: npm-registry
        url: https://npm.pkg.github.com
        token: ${{ secrets.DEPENDABOT_GH_NPM_TOKEN }}

updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
      ignore:
          - dependency-name: '*'
            update-types: ['version-update:semver-major']
      groups:
          root-dependencies:
              patterns:
                  - '*'
      target-branch: 'stage'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'shared'
      schedule:
          interval: 'weekly'
          day: 'monday'
      ignore:
          - dependency-name: '*'
            update-types: ['version-update:semver-major']
      groups:
          shared-dependencies:
              patterns:
                  - '*'
      target-branch: 'stage'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'client'
      registries:
          - github-packages
      schedule:
          interval: 'weekly'
          day: 'monday'
      ignore:
          - dependency-name: '*'
            update-types: ['version-update:semver-major']
      groups:
          client-dependencies:
              patterns:
                  - '*'
      target-branch: 'stage'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'npm'
      directory: 'server'
      registries:
          - github-packages
      schedule:
          interval: 'weekly'
          day: 'monday'
      ignore:
          - dependency-name: '*'
            update-types: ['version-update:semver-major']
          - dependency-name: 'ioredis'
      groups:
          server-dependencies:
              patterns:
                  - '*'
      target-branch: 'stage'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'docker'
      directory: 'client'
      schedule:
          interval: 'weekly'
          day: 'monday'
      groups:
          client-docker:
              patterns:
                  - '*'
      target-branch: 'stage'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'docker'
      directory: 'server'
      schedule:
          interval: 'weekly'
          day: 'monday'
      groups:
          server-docker:
              patterns:
                  - '*'
      target-branch: 'stage'
      assignees:
          - 'aditya-arcot'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
          day: 'monday'
      groups:
          github-actions:
              patterns:
                  - '*'
      target-branch: 'stage'
      assignees:
          - 'aditya-arcot'
