name: ${REPO?}

services:
    server:
        image: ${SERVER_IMAGE?}
        container_name: ${SERVER_CONTAINER?}
        restart: unless-stopped
        ports:
            - '${SERVER_PORT?}:3000'
            - '${WEBHOOK_PORT?}:3001'

    client:
        image: ${CLIENT_IMAGE?}
        container_name: ${CLIENT_CONTAINER?}
        restart: unless-stopped
        ports:
            - '${CLIENT_PORT?}:80'
