name: Bump and Publish Shared Package after Dependabot Merge

on:
    pull_request:
        branches:
            - stage
        types:
            - closed
        paths:
            - 'shared/package.json'
            - 'shared/package-lock.json'

permissions:
    contents: write
    packages: write

jobs:
    bump-and-publish:
        if: >
            github.event.pull_request.merged == true &&
            github.event.pull_request.user.login == 'dependabot[bot]'
        runs-on: self-hosted
        steps:
            - name: checkout
              uses: actions/checkout@v6

            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
                  check-latest: true
                  registry-url: 'https://npm.pkg.github.com'

            - name: update npm
              run: npm i -g npm@latest

            - name: fetch, rebase
              run: |
                  git fetch
                  git rebase

            - name: bump version
              working-directory: shared
              run: |
                  npm config ls
                  npm version patch

            - name: commit, push changes
              working-directory: shared
              run: |
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"
                  git config list

                  git add package.json package-lock.json
                  git status

                  git commit -m "bump shared package version after dependabot merge"
                  git push

            - name: install, build
              working-directory: shared
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm config ls
                  npm ci --cache .npm
                  npm run build

            - name: publish
              working-directory: shared
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm config ls
                  npm whoami --registry=https://npm.pkg.github.com/
                  npm publish --access public

            - name: remove cache folder
              if: always()
              working-directory: shared
              run: rm -rf .npm
