name: Run Tests

on:
    workflow_dispatch:
    pull_request_target:
        branches:
            - test
            - stage
            - main

permissions:
    packages: read

jobs:
    test-server:
        runs-on: self-hosted
        environment: ${{ github.base_ref == 'main' && 'prod' || github.base_ref || github.ref_name }}
        steps:
            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
                  check-latest: true
                  registry-url: 'https://npm.pkg.github.com'

            - name: update npm
              run: npm i -g npm@latest

            - name: create .env
              working-directory: server
              run: |
                  echo "CLIENT_LOGTAIL_TOKEN=${{ secrets.CLIENT_LOGTAIL_TOKEN }}" >> .env
                  echo "SERVER_LOGTAIL_TOKEN=${{ secrets.SERVER_LOGTAIL_TOKEN }}" >> .env

                  echo "REDIS_HOST=host.docker.internal" >> .env
                  echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env

                  echo "DB_HOST=host.docker.internal" >> .env
                  echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
                  echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
                  echo "DB_USER=${{ secrets.DB_USER }}" >> .env
                  echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

                  echo "CSRF_SECRET=${{ secrets.CSRF_SECRET }}" >> .env
                  echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env

                  echo "PLAID_CLIENT_ID=${{ secrets.PLAID_CLIENT_ID }}" >> .env
                  echo "PLAID_SECRET=${{ secrets.PLAID_SECRET }}" >> .env
                  echo "PLAID_WEBHOOK_URL=${{ secrets.PLAID_WEBHOOK_URL }}" >> .env

                  echo "DEMO_USER=${{ secrets.DEMO_USER }}" >> .env

                  echo "DOCKER_REGISTRY=${{ secrets.DOCKER_REGISTRY }}" >> .env

                  echo "LOG_LEVEL=${{ vars.LOG_LEVEL }}" >> .env

                  echo "NODE_ENV=${{ vars.NODE_ENV }}" >> .env
                  echo "PLAID_ENV=${{ vars.PLAID_ENV }}" >> .env

                  echo "CLIENT_PORT=${{ vars.CLIENT_PORT }}" >> .env
                  echo "SERVER_PORT=${{ vars.SERVER_PORT }}" >> .env
                  echo "WEBHOOK_PORT=${{ vars.WEBHOOK_PORT }}" >> .env

            - name: install
              working-directory: server
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm config ls
                  npm ci --cache .npm

            - name: run tests
              working-directory: server
              run: |
                  npm config ls
                  npm run test:deploy

            - name: remove cache folder
              if: always()
              working-directory: server
              run: rm -rf .npm

    test-shared:
        runs-on: self-hosted
        environment: ${{ github.base_ref == 'main' && 'prod' || github.base_ref || github.ref_name }}
        steps:
            - name: checkout
              uses: actions/checkout@v6
              with:
                  ref: ${{ github.event.pull_request.head.sha || github.ref_name }}

            - name: setup node
              uses: actions/setup-node@v6
              with:
                  node-version: 'lts/*'
                  check-latest: true
                  registry-url: 'https://npm.pkg.github.com'

            - name: update npm
              run: npm i -g npm@latest

            - name: install
              working-directory: shared
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  npm config ls
                  npm ci --cache .npm

            - name: run tests
              working-directory: shared
              run: |
                  npm config ls
                  npm run test:deploy

            - name: remove cache folder
              if: always()
              working-directory: shared
              run: rm -rf .npm
